# Generated by Django 3.2.7 on 2021-09-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discografia',
            options={'ordering': ['created'], 'verbose_name': 'aplicacion', 'verbose_name_plural': 'aplicaciones'},
        ),
    ]
