# Generated by Django 3.2.7 on 2021-09-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_discografia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discografia',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='discografia',
            name='image',
            field=models.ImageField(upload_to='discografia', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='discografia',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
